version: '3'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  server:
    build: server
    volumes:
      - ./server:/app
    ports:
      - 5000:5000
    depends_on:
      - rabbitmq


  worker:
    build: worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq